<?php

    echo '<table border="1" style="text-align:center">';
      echo '<tr>';
        echo '<th colspan="4"><h1>Solicitud de Ingreso a la Universidad</h1></th>';
      echo '</tr>';
      echo '<tr>';
        echo'<td>';
         echo  $_POST["ApellidoPatern"];
        echo '</td>';
        echo'<td>';
         echo  $_POST["ApellidoMatern"];
        echo '</td>';
        echo '<td colspan="2">';
         echo $_POST["Nombre"];
        echo '</td>';
      echo '</tr>';
      echo '<tr>';
        echo'<th><strong><u>Apellido Paterno</u></strong></th>';
        echo '<th><strong><u>Apellido Materno</u></strong></th>';
        echo '<th colspan="2"><strong><u>Nombre(s)</u></strong></th>';
      echo '</tr>';
      echo '<tr>';
        echo '<th><strong><u>Sexo:</u></strong></th>';
        echo '<td>';
         echo $_POST["Sexo"];
        echo '</td>';
        echo '<th><strong><u>Edad:</u></strong></th>';
        echo '<td>';
         echo $_POST["Edad"];
        echo '</td>';
      echo'</tr>';
      echo '<tr>';
        echo '<td colspan="2">';
         echo $_POST["Correo"];
        echo '</td>';
        echo '<td>';
         echo $_POST["Telefono"];
        echo '</td>';
        echo '<td>';
         echo $_POST["Celular"];
        echo '</td>';
      echo '</tr>';
      echo '<tr>';
        echo '<th colspan="2"><strong><u>Correo Electrónico</u></strong></th>';
        echo '<th><strong><u>Teléfono</u></strong></th>';
        echo '<th><strong><u>Celular</u></strong></th>';
      echo '</tr>';
      echo '<tr>';
        echo '<th><strong><u>Escuela de Procedencia:</u></strong></th>';
        echo '<td>';
         echo $_POST["EscueladeProcedencia"];
        echo '</td>';
        echo '<th><strong><u>Promedio:</u></strong></th>';
        echo '<td>';
         echo $_POST["Promedio"];
        echo '</td>'; 
      echo '</tr>';
      echo '<tr>';
        echo '<th colspan="2"><strong><u>Primera Opción:</u></strong></th>';
        echo '<td colspan="2">';
         echo $_POST["PrimeraOp"];
        echo '</td>';
      echo '</tr>';
      echo '<tr>';
        echo '<th colspan="2"><strong><u>Segunda Opción:</u></strong></th>';
        echo '<td colspan="2">';
         echo $_POST["SegundaOp"]; 
        echo '</td>';
      echo '</tr>';
    echo '</table>';
?>